version: "3.0"

services:
  project-zomboid:
    image: cyrale/project-zomboid
    restart: unless-stopped
    environment:
      SERVER_NAME: "GLORYHOLE"
      SERVER_PUBLIC_NAME: "GLORY HOLE"
      SERVER_PASSWORD: "helloworldz2"
      ADMIN_PASSWORD: "helloworldzxc"
    ports:
      - target: 16261
        published: 16261
        protocol: udp
      - target: 16262
        published: 16262
        protocol: udp
      - target: 27015
        published: 27015
        protocol: tcp
    volumes:
      - ./server-data:/server-data
      
