version: "3.0"

services:
  project-zomboid:
    image: cyrale/project-zomboid
    restart: unless-stopped
    environment:
      SERVER_NAME: "GLORYHOLE"
      SERVER_PUBLIC_NAME: "GLORY HOLE"
      SERVER_PASSWORD: "helloworldz2"
      ADMIN_PASSWORD: "helloworldzxc"
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262-16272:16262-16272"
      - "16262:16272/udp"
      - "27015:27015"
    volumes:
      - ./server-data:/server-data
      
